# Задание 1
Создайте numpy array с элементами от числа N до 0

In [1]:
import numpy as np
from numpy import linalg

In [2]:
N = 10
np.arange(N, -1, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [3]:
N = 10
matrix = np.diag(np.arange(N, 0, -1))
# создаем единичную матрицу
sum([column[row] for row, column in enumerate(matrix)])
# считаем сумму по диагонали

55

# Задание 3
Решите систему уравнений:

    4x + 2y + z = 4
    x + 3y = 12
    5y + 4z = -3

In [4]:
a = np.array( [ [4, 2, 1], [0, 3, 0], [5, 4, 0] ] )
# коэффициенты из левой части
b = np.array( [4, 12, -3] )
# значения из правой части
np.linalg.solve(a, b)

array([-3.8,  4. , 11.2])

In [5]:
# проверка на корректность
np.allclose(np.dot(a, linalg.solve(a, b)), b)

True

# Задание 4
В материалах занятия раздел “Задача 4 домашнего задания”

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [6]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

def cosine():
    for vector in users_stats:
#         обращение к каждому вектору
        users_stats_len = np.linalg.norm(vector)
        next_user_stats_len = np.linalg.norm(next_user_stats)
#         опеределение длины векторов 
    return np.dot(users_stats, next_user_stats) / (users_stats_len * next_user_stats_len)
# подсчет конусного сходства
cosine()

array([0.09534626, 0.47673129, 0.19069252, 0.47673129, 0.19069252,
       0.        , 0.        , 0.28603878, 0.        , 0.        ])